"""
Correlation IDs, the thing a monolith never needed and a microservice
platform cannot function without.

In the monolith, one purchase was one Python call stack. A traceback told
you everything. Split across seven services, that same purchase is now
seven separate log streams on seven separate pods, and the only way to
reassemble "what happened to this transaction" is a shared identifier that
travels with the request across every hop.

Two identifiers, deliberately distinct, because they answer different
questions and have different lifetimes:

  correlation_id  -- minted once by api-gateway, propagated UNCHANGED
                     through every downstream call, including the SOAP hop
                     into ACE and back. Answers "show me everything that
                     happened for this one client request."

  rrn             -- the ISO 8583 Retrieval Reference Number, generated by
                     transaction-service, and the business key the switch,
                     the ledger, and the settlement file all agree on.
                     Answers "show me this transaction" long after the logs
                     have rotated away.

Do not conflate them. A correlation_id exists for requests that never
become transactions at all (a declined risk check, a 401). An RRN exists
for money that moved and must still be findable in seven years.

NOTE ON contextvars: request_id_var is a ContextVar, not a global or a
thread-local. FastAPI runs handlers on an asyncio event loop where many
requests share one thread, a threading.local() here would leak one
request's ID into another's logs, intermittently, under load. That is a
genuinely nasty bug class, and ContextVar is the thing that prevents it.
"""

import contextvars
import json
import logging
import time
import uuid

CORRELATION_HEADER = "X-Correlation-ID"
CAUSATION_HEADER = "X-Causation-ID"

_correlation_id: contextvars.ContextVar[str] = contextvars.ContextVar(
    "correlation_id", default="-"
)


def new_correlation_id() -> str:
    return f"cid-{uuid.uuid4().hex[:16]}"


def set_correlation_id(value: str) -> None:
    _correlation_id.set(value)


def get_correlation_id() -> str:
    return _correlation_id.get()


def outbound_headers(extra: dict | None = None) -> dict:
    """Headers every service-to-service call must carry. Forgetting this on
    one call is what produces a trace with a hole in the middle."""
    headers = {CORRELATION_HEADER: get_correlation_id()}
    if extra:
        headers.update(extra)
    return headers


# Computed once. time.localtime() per log record would be a syscall on a hot
# path to produce a value that does not change.
_TZ_OFFSET = time.strftime("%z")


class CorrelationIdFilter(logging.Filter):
    """Injects the current correlation ID into every log record, so handlers
    never have to remember to include it, one forgotten log line is one
    invisible step in a trace."""

    def filter(self, record: logging.LogRecord) -> bool:
        record.correlation_id = get_correlation_id()
        return True


class JsonLogFormatter(logging.Formatter):
    """
    One JSON object per line, built with json.dumps.

    NOT a format string. The previous version interpolated the message
    directly into a JSON document, so any message containing a quote, a
    backslash or a newline produced a line that would not parse. On a single
    local run 38 of 59 lines were invalid, which nothing noticed because
    nothing had tried to read them back until the scenario runner did.
    """

    def __init__(self, service_name: str):
        super().__init__(datefmt="%Y-%m-%dT%H:%M:%S")
        self.service_name = service_name

    def format(self, record: logging.LogRecord) -> str:
        payload = {
            # Milliseconds matter: a purchase crosses five services in tens
            # of them, and at one-second resolution a reconstructed flow
            # cannot be ordered. The offset is appended here rather than via
            # strftime %z because strftime formats the whole timestamp in one
            # pass and would put the offset before the milliseconds.
            "ts": f"{self.formatTime(record, self.datefmt)}"
                  f".{int(record.msecs):03d}{_TZ_OFFSET}",
            "level": record.levelname,
            "service": self.service_name,
            "correlation_id": getattr(record, "correlation_id", "-"),
            "logger": record.name,
            "message": record.getMessage(),
        }
        if record.exc_info:
            # As a FIELD, not spliced into the message. A traceback is
            # multi-line, and pasting one into a single-line record turned
            # one error into several lines that no parser could read.
            payload["exception"] = self.formatException(record.exc_info)
        if record.stack_info:
            payload["stack"] = self.formatStack(record.stack_info)
        return json.dumps(payload, default=str)


def configure_logging(service_name: str, level: str = "INFO") -> logging.Logger:
    """
    Structured, single-line, correlation-tagged logging. Every service calls
    this once at startup so all seven produce a format that can be grepped
    and aggregated identically, and, since the formatter below, actually
    parsed.
    """
    handler = logging.StreamHandler()
    handler.addFilter(CorrelationIdFilter())
    handler.setFormatter(JsonLogFormatter(service_name))

    root = logging.getLogger()
    root.handlers.clear()
    root.addHandler(handler)
    root.setLevel(level.upper())
    return logging.getLogger(service_name)
