"""
Correlation IDs, the thing a monolith never needed and a microservice
platform cannot function without.

In the monolith, one purchase was one Python call stack. A traceback told
you everything. Split across seven services, that same purchase is now
seven separate log streams on seven separate pods, and the only way to
reassemble "what happened to this transaction" is a shared identifier that
travels with the request across every hop.

Two identifiers, deliberately distinct, because they answer different
questions and have different lifetimes:

  correlation_id  -- minted once by api-gateway, propagated UNCHANGED
                     through every downstream call, including the SOAP hop
                     into ACE and back. Answers "show me everything that
                     happened for this one client request."

  rrn             -- the ISO 8583 Retrieval Reference Number, generated by
                     transaction-service, and the business key the switch,
                     the ledger, and the settlement file all agree on.
                     Answers "show me this transaction" long after the logs
                     have rotated away.

Do not conflate them. A correlation_id exists for requests that never
become transactions at all (a declined risk check, a 401). An RRN exists
for money that moved and must still be findable in seven years.

NOTE ON contextvars: request_id_var is a ContextVar, not a global or a
thread-local. FastAPI runs handlers on an asyncio event loop where many
requests share one thread, a threading.local() here would leak one
request's ID into another's logs, intermittently, under load. That is a
genuinely nasty bug class, and ContextVar is the thing that prevents it.
"""

import contextvars
import logging
import uuid

CORRELATION_HEADER = "X-Correlation-ID"
CAUSATION_HEADER = "X-Causation-ID"

_correlation_id: contextvars.ContextVar[str] = contextvars.ContextVar(
    "correlation_id", default="-"
)


def new_correlation_id() -> str:
    return f"cid-{uuid.uuid4().hex[:16]}"


def set_correlation_id(value: str) -> None:
    _correlation_id.set(value)


def get_correlation_id() -> str:
    return _correlation_id.get()


def outbound_headers(extra: dict | None = None) -> dict:
    """Headers every service-to-service call must carry. Forgetting this on
    one call is what produces a trace with a hole in the middle."""
    headers = {CORRELATION_HEADER: get_correlation_id()}
    if extra:
        headers.update(extra)
    return headers


class CorrelationIdFilter(logging.Filter):
    """Injects the current correlation ID into every log record, so handlers
    never have to remember to include it, one forgotten log line is one
    invisible step in a trace."""

    def filter(self, record: logging.LogRecord) -> bool:
        record.correlation_id = get_correlation_id()
        return True


def configure_logging(service_name: str, level: str = "INFO") -> logging.Logger:
    """
    Structured, single-line, correlation-tagged logging. Every service calls
    this once at startup so all seven produce a format that can be grepped
    and aggregated identically.
    """
    handler = logging.StreamHandler()
    handler.addFilter(CorrelationIdFilter())
    handler.setFormatter(
        logging.Formatter(
            fmt=(
                '{"ts":"%(asctime)s","level":"%(levelname)s",'
                f'"service":"{service_name}",'
                '"correlation_id":"%(correlation_id)s",'
                '"logger":"%(name)s","message":"%(message)s"}'
            ),
            datefmt="%Y-%m-%dT%H:%M:%S%z",
        )
    )

    root = logging.getLogger()
    root.handlers.clear()
    root.addHandler(handler)
    root.setLevel(level.upper())
    return logging.getLogger(service_name)
